{
  try {
    functionAssertions.assertFunction(projection,UNKNOWN,null);
    fail("Expected to throw an INVALID_CAST_ARGUMENT exception");
  }
 catch (  PrestoException e) {
    assertEquals(e.getErrorCode(),INVALID_CAST_ARGUMENT.toErrorCode());
  }
}
