{
  try {
    retry().stopOnIllegalExceptions().runUnchecked(new Callable<Void>(){
      @Override public Void call() throws Exception {
        storageManager.dropShard(shardId);
        return null;
      }
    }
);
  }
 catch (  Exception e) {
    log.error(e,"shard drop failed");
  }
}
