{
  PrestoException exception=new PrestoException(new ErrorCode(0,"test"),"test");
  Assert.assertEquals(exception.getMessage(),"test");
  exception=new PrestoException(new ErrorCode(0,"test"),new RuntimeException("test2"));
  Assert.assertEquals(exception.getMessage(),"test2");
  exception=new PrestoException(new ErrorCode(0,"test"),new RuntimeException());
  Assert.assertEquals(exception.getMessage(),"test");
}
