{
  PrestoException exception=new PrestoException(new TestErrorCode(),"test");
  Assert.assertEquals(exception.getMessage(),"test");
  exception=new PrestoException(new TestErrorCode(),new RuntimeException("test2"));
  Assert.assertEquals(exception.getMessage(),"test2");
  exception=new PrestoException(new TestErrorCode(),new RuntimeException());
  Assert.assertEquals(exception.getMessage(),"test");
}
