{
  tester.recordCalled("error");
  throw new RuntimeException("test error from procedure");
}
