{
  try {
    assertFunction(projection,expectedType,null);
    fail(format("Expected to throw %s exception",expectedErrorCode.toErrorCode()));
  }
 catch (  PrestoException e) {
    assertEquals(e.getErrorCode(),expectedErrorCode.toErrorCode());
  }
}
