{
  try {
    FunctionAssertions.assertFilter(filter,expected);
  }
 catch (  Throwable e) {
    throw new RuntimeException("Error processing " + filter,e);
  }
  return null;
}
