{
  assertTrue(expectedState.isDone());
  assertState(stateMachine,expectedState,expectedException);
  assertFalse(stateMachine.transitionToPlanning());
  assertState(stateMachine,expectedState,expectedException);
  assertFalse(stateMachine.transitionToStarting());
  assertState(stateMachine,expectedState,expectedException);
  assertFalse(stateMachine.transitionToRunning());
  assertState(stateMachine,expectedState,expectedException);
  assertFalse(stateMachine.transitionToFinishing());
  assertState(stateMachine,expectedState,expectedException);
  assertFalse(stateMachine.transitionToFailed(FAILED_CAUSE));
  assertState(stateMachine,expectedState,expectedException);
  assertFalse(stateMachine.transitionToFailed(new IOException("failure after finish")));
  assertState(stateMachine,expectedState,expectedException);
}
